version: '3.7'
services:
  API:
    image: 'vehicle-station-management-1.0.jar'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/vehicle_station_management
      - SPRING_DATASOURCE_USERNAME=vehicle_station_management
      - SPRING_DATASOURCE_PASSWORD=vehicle_station_management

  PostgreSQL:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=vehicle_station_management
      - POSTGRES_USER=vehicle_station_management
      - POSTGRES_DB=vehicle_station_management
    restart: always
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./scripts/00_create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql