spring:
  application:
    name: vehicle-station-management


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.122.242:5432/vehicle_station_management
    username: vehicle_station_management
    password: vehicle_station_management
    driverClassName: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  jackson:
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
